# Test the simulation code.  Basically threwe functions,
# Clone, Tunmor, and generateData

library(CloneFinder)
set.seed(523476)  # for reproducible tests

######### CLONE #########
# The Clone function is the constructor for the class with
# the same name. There are two options to test.

# 1. You can use rthe default weights, or specify them explicitly

# example: default weights = equal prevalences of compartments
clone <- Clone(10000)
clone@weights
table(clone@segments)
rm(clone)

# example: highly biased weights = prevalences of compartments
wts <- rev(5^(1:5))
wts <- wts/sum(wts)  # we reuse this in next test
clone <- Clone(10000, wts)
clone@weights
table(clone@segments)
head(clone@segments)   # note that the names are autogenerated
rm(clone)

# 2. You can pass in segment names or (as above) use the defaults

clone <- Clone(500, wts, paste("S", 1:500, sep=''))
head(clone@segments)
rm(clone)

# obvious things that might break -- these are wrapped in 'try'
# calls so that R CMD check doesn't fail

# non-positive number of segments
try( Clone(-1) )
try( Clone(0) )
# bad weights
try( Clone(100, NULL) )
try( Clone(100, NA) )
try( Clone(100, "x") )
try( Clone(100, c(-1, 2, 3)) )
# bad segfment names
try( Clone(500, wts, paste("S", 1:100, sep='')) )
try( Clone(100, wts, paste("S", 1:500, sep='')) )

######### Tumor #########
# Note: In order to create a Tumor, you must have already created
# a CompartmentModel.

# Use known compartment centers
xy <- data.frame(x = c(.2, .7, .8, .1, .4),
                 y = c(.2, .3, .5, .9, .7))
# Just pass in the number of segments and simulate the markers-per-segment
baseModel <- CompartmentModel(200, xy, 0.25)
summary(baseModel@markers)

# example: tumor with two clones of unequal prevalence (0.75, 0.25)
tumor <- Tumor(baseModel, c(3,1), wts)
tumor@fraction
tumor@weights

tdata <- tumor@data
summary(tdata)
table(A=tdata[,1], B=tdata[,2])

head(tumor@data)
head(tumor@compartments)
head(tumor@centers)

rm(tumor, tdata)

# example: specifying segment lengths
segs <- runif(300, 20, 3000)
baseModel <- CompartmentModel(segs, xy, 0.25)
summary(baseModel@markers)
rm(segs)

tumor <- Tumor(baseModel, c(3,1), wts)
tumor@fraction
tumor@weights

tdata <- tumor@data
summary(tdata)
table(A=tdata[,1], B=tdata[,2])

head(tumor@data)
head(tumor@compartments)
head(tumor@centers)

rm(baseModel, tdata, xy, wts)

# use the last example to generate data


