doOldTests <- function() {
  # Test the simulation code.  Basically threwe functions,
# Clone, Tunmor, and generateData

library(CloneFinder)
set.seed(523476)  # for reproducible tests

######### CLONE #########
# The Clone function is the constructor for the class with
# the same name. There are two options to test.

# 1. You can use rthe default weights, or specify them explicitly

# example: default weights = equal prevalences of compartments
clone <- Clone(10000)
clone@weights
table(clone@segments)
rm(clone)

# example: highly biased weights = prevalences of compartments
wts <- rev(5^(1:5))
wts <- wts/sum(wts)  # we reuse this in next test
clone <- Clone(10000, wts)
clone@weights
table(clone@segments)
head(clone@segments)   # note that the names are autogenerated
rm(clone)

# 2. You can pass in segment names or (as above) use the defaults

clone <- Clone(500, wts, paste("S", 1:500, sep=''))
head(clone@segments)
rm(clone)

# obvious things that might break -- these are wrapped in 'try'
# calls so that R CMD check doesn't fail

# non-positive number of segments
try( Clone(-1) )
try( Clone(0) )
# bad weights
try( Clone(100, NULL) )
try( Clone(100, NA) )
try( Clone(100, "x") )
try( Clone(100, c(-1, 2, 3)) )
# bad segfment names
try( Clone(500, wts, paste("S", 1:100, sep='')) )
try( Clone(100, wts, paste("S", 1:500, sep='')) )

######### Tumor #########
# Note: In order to create a Tumor, you must have already created
# a CompartmentModel.

# Use known compartment centers
xy <- data.frame(x = c(.2, .7, .8, .1, .4),
                 y = c(.2, .3, .5, .9, .7))
# Just pass in the number of segments and simulate the markers-per-segment
baseModel <- CompartmentModel(200, xy, 0.25)
summary(baseModel@markers)

# example: tumor with two clones of unequal prevalence (0.75, 0.25)
tumor <- Tumor(baseModel, c(3,1), wts)
tumor@fraction
tumor@weights

tdata <- tumor@data
summary(tdata)
table(A=tdata[,1], B=tdata[,2])

head(tumor@data)
head(tumor@compartments)
head(tumor@centers)

rm(tumor, tdata)

# example: specifying segment lengths
segs <- runif(300, 20, 3000)
baseModel <- CompartmentModel(segs, xy, 0.25)
summary(baseModel@markers)
rm(segs)

tumor <- Tumor(baseModel, c(3,1), wts)
tumor@fraction
tumor@weights

tdata <- tumor@data
summary(tdata)
table(A=tdata[,1], B=tdata[,2])

head(tumor@data)
head(tumor@compartments)
head(tumor@centers)

rm(baseModel, tdata, xy, wts)

# use the last example to generate data
simdata <- generateData(tumor)

phi <- sampleSimplex(1, 5)
likely(simdata, phi, tumor)

  
  library(CloneFinder)

set.seed(363453)

# generate the markers explicitly
nSeg <- 1000
markers <- round(runif(nSeg, 25, 1000))
# Centers needed to define the pure structure
xy <- data.frame(x = c(.2, .7, .8, .1, .4),
                 y = c(.2, .3, .5, .9, .7))
# start by creating the compartment model
baseModel <- CompartmentModel(markers, xy, sigma0=0.25)
rm(xy, nSeg, markers)

# Now we set up an abstract tumnor
wts <- rev(5^(1:5))
wts <- wts/sum(wts)
fracs <- c(5, 3, 1)
TrueNclones <- length(fracs)
# now simulate a tumor; length of 'fracs' in first argument is number of clones
tumor <- Tumor(baseModel, fracs, wts)
rm(wts, fracs)
ls()

# simulate data by selecting the weighted means with appropriate
# standard error of the mean
simdata <- generateData(tumor)

firstPass <- PrefitCloneModel(simdata, baseModel)
plot(firstPass)
hist(firstPass, breaks=123)
summary(firstPass)

  library(CloneFinder)

#############
# check that 'forward' works for both vectors and matrices
# and that it returns a value of the same type
mat <- matrix(c(0.6, 0.3, 0.1, 0.2, 0.3, 0.5), byrow=TRUE, ncol=3)
vec <- mat[1,]
CloneFinder:::forward(mat)
CloneFinder:::forward(vec)
class(CloneFinder:::forward(vec))
rm(mat, vec)

# check forward and backward for both vectors and matrices
# matrix input
mat <- matrix(c(0.6, 0.3, 0.1, 0.2, 0.3, 0.5), byrow=TRUE, ncol=3)
fm <- CloneFinder:::forward(mat)
bm <- CloneFinder:::backward(fm)
all(round(mat - bm, 15)==0) # round-trip agrees to 15 decimal places

# vector input
vec <- mat[1,]
fv <- CloneFinder:::forward(vec)
bv <- CloneFinder:::backward(fv)
class(bv)
all(round(vec - bv, 15)==0) # round-trip agrees to 15 decimal places

# bigger matrix
x <- runif(10000, 0, 1)
V <- matrix(CloneFinder:::lp(x), ncol=4)
F <- CloneFinder:::backward(V) # nonneg and sum to 1
temp <- apply(F, 1, sum)
summary(temp)

w <- CloneFinder:::forward(F)
flap <- CloneFinder:::backward(w)
summary(as.vector(F - flap))
rm(mat, fm, bm, vec, fv, bv, x, V, F, temp, w, flap)

#############
# check vectorization formula
Zs <- array(1:60, dim=c(4, 5, 3))
psi <- 1:3
y <- sweep(Zs, 3, psi, "*")
phinew <- apply(y, 1:2, sum)
phinew
rm(Zs, psi, y, phinew)


#############
# check array dimensions in edge case
#
# precomputeZed works okay
zary2 <- CloneFinder:::precomputeZed(5, 2)
dim(zary2)
zary1 <- CloneFinder:::precomputeZed(5, 1)
dim(zary1)

#############
# simulate a sample data set
set.seed(8644458)
xy <- data.frame(x = log10(c(2, 2, 1, 3, 4)/2),
                 y = c(1/2, 0, 0, 1/3, 1/4))
markers <- round(runif(1000, 25, 1000))
compModel <- CompartmentModel(markers, xy, 0.25)
wts <- rev(5^(1:5))
wts <- wts/sum(wts)
psis <- c(0.6, 0.3, 0.1)
tumor <- Tumor(compModel, psis, wts)
dataset <- generateData(tumor)

Z2 <- CloneFinder:::setZs(c(0.5, 0.5), zary2, dataset, compModel)
dim(Z2)

Z1 <- CloneFinder:::setZs(1, zary1, dataset, compModel)
dim(Z1)

library(CloneFinder)

#############################
# simulate a sample data set
set.seed(539121)
# pure centers
xy <- data.frame(x = log10(c(2, 2, 1, 3, 4)/2),
                 y = c(1/2, 0, 0, 1/3, 1/4))
plot(xy, pch=16)
# number of segments
nSeg <- 1000
# number of SNP markers per segment
markers <- round(runif(nSeg, 25, 1000))
compModel <- CompartmentModel(markers, xy, 0.25)
# probability of a pure clonal segment in each compartment
wts <- rev(5^(1:5))
wts <- wts/sum(wts)
# percentage of cells in each (of three) clone(s)
psis <- c(0.6, 0.3, 0.1)

tumor <- Tumor(compModel, psis, wts)
dataset <- generateData(tumor)

# prefit the model
pcm <- PrefitCloneModel(dataset, tumor)
# good guess at psi-vector
estpsi <- guessPsi(pcm, 3) # 3 is number of clones we aqre trying to fit
estpsi
# refine with EM-algorithm
final <- runEMalg(estpsi, dataset, tumor)
final$psi
final$loglike

Zed <- trueZ(tumor)
align <- Zed - final$Zmats

gotit <- apply(align, 1, function(x) all(x==0))
mean(gotit)

  library(CloneFinder)

#############################
# simulate a sample data set
set.seed(539121)
# pure centers
xy <- data.frame(x = log10(c(2, 2, 1, 3, 4)/2),
                 y = c(1/2, 0, 0, 1/3, 1/4))
# small number of segments
nSeg <- 10
# number of SNP markers per segment
markers <- round(runif(nSeg, 25, 1000))
compModel <- CompartmentModel(markers, xy, 0.25)
# probability of a pure clonal segment in each compartment
wts <- rev(5^(1:5))
wts <- wts/sum(wts)
# percentage of cells in each (of three) clone(s)
psis <- c(0.6, 0.3, 0.1)

tumor <- Tumor(compModel, psis, wts)
dataset <- generateData(tumor)

# prefit the model
pcm <- PrefitCloneModel(dataset, tumor)
#############################
# now test the posterior distributions

post <- posteriorPhi(pcm)
dim(post) # segments by phi-vectors
summary(apply(post, 1, sum)) # all 1's

dataset # pure normal for 1, 2, 3
# should make this an exported function
phi0 <- c(1,0,0,0,0) # euclidean distance from normal vertex
plotPosteriorCDF(pcm, phi0, irow=1, post=post, type='l')
plotPosteriorCDF(pcm, phi0, irow=8, post=post, type='l')


# radii needed to acheive a given quantile of posterior probability
postq <- posteriorQuantile(pcm, phi0=phi0, post=post)
postq

# probability of true phi being within a given radius of a phi-vector
pr <- posteriorRegion(pcm, radius=c(0.05, 0.10), phi0=phi0, post=post)
round(pr, 3)


}
